// Get Movies constants
export const GET_MOVIES_INIT = "GET_MOVIES_INIT"
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS"
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED"

//Get Movie by id constants
export const GET_MOVIE_BY_ID_INIT = "GET_MOVIE_BY_ID_INIT"
export const GET_MOVIE_BY_ID_SUCCESS = "GET_MOVIE_BY_ID_SUCCESS"
export const GET_MOVIE_BY_ID_FAILED = "GET_MOVIE_BY_ID_FAILED"

//Get Movies by search
export const GET_MOVIE_BY_SEARCH_INIT = "GET_MOVIE_BY_SEARCH_INIT"
export const GET_MOVIE_BY_SEARCH_SUCCESS = "GET_MOVIE_BY_SEARCH_SUCCESS"
export const GET_MOVIE_BY_SEARCH_FAILED = "GET_MOVIE_BY_SEARCH_FAILED"


//Get Movies Credit
export const GET_MOVIE_CREDIT_INIT = "GET_MOVIE_CREDIT_INIT"
export const GET_MOVIE_CREDIT_SUCCESS = "GET_MOVIE_CREDIT_SUCCESS"
export const GET_MOVIE_CREDIT_FAILED = "GET_MOVIE_CREDIT_FAILED"


//Get Similar Movies
export const GET_SIMILAR_MOVIE_INIT = "GET_SIMILAR_MOVIE_INIT"
export const GET_SIMILAR_MOVIE_SUCCESS = "GET_SIMILAR_MOVIE_SUCCESS"
export const GET_SIMILAR_MOVIE_FAILED = "GET_SIMILAR_MOVIE_FAILED"

export const API_PREFIX = "https://api.themoviedb.org/3"
